# Generated by Django 3.0.2 on 2020-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('todo_type', models.CharField(blank=True, choices=[('p', 'personal'), ('s', 'school'), ('w', 'work'), ('f', 'family'), ('m', 'misc')], default='m', max_length=1)),
            ],
            options={
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
