# Generated by Django 3.0.2 on 2020-01-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter_url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorter_url',
            name='shorty',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
